version: '3'

networks:
  private:
    external: true

services:
  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    networks:
      - private
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
